### ISSUE TITLE
Dev Container cannot start

### ISSUE THREAD

**Issue by cZalyun** [95gabor/book-store#161]
clicked on the devcontainer label in the readme, it opened a freshly installed vscode installed the docker extension then started to setting up the container, then an error occurred.

docker desktop 4.30
Mac os 14 (arm mac)

`[59975 ms] Start: Run: docker compose --project-name book-store -f /workspaces/book-store/docker-compose.yaml -f /workspaces/book-store/.devcontainer/docker-compose.extend.yaml -f /tmp/devcontainercli-root/docker-compose/docker-compose.devcontainer.build-1717443659232.yml -f /tmp/devcontainercli-root/docker-compose/docker-compose.devcontainer.containerFeatures-1717443659252-03bd058d-53e2-4935-b34b-381f8175cd03.yml up -d --no-recreate
[+] Running 1/2
 ⠿ Container book-store-database-1    Running                                                                                                                 0.0s
 ⠇ Container book-store-book-store-1  Starting                                                                                                                1.8s
Error response from daemon: error while creating mount source path '/host_mnt/System/Volumes/Data/home/node/app/.prettierrc': mkdir /host_mnt/System/Volumes/Data/home/node: operation not supported
[61879 ms] Error: Command failed: docker compose --project-name book-store -f /workspaces/book-store/docker-compose.yaml -f /workspaces/book-store/.devcontainer/docker-compose.extend.yaml -f /tmp/devcontainercli-root/docker-compose/docker-compose.devcontainer.build-1717443659232.yml -f /tmp/devcontainercli-root/docker-compose/docker-compose.devcontainer.containerFeatures-1717443659252-03bd058d-53e2-4935-b34b-381f8175cd03.yml up -d --no-recreate
[61879 ms]     at QtA (/root/.vscode-remote-containers/dist/dev-containers-cli-0.362.0/dist/spec-node/devContainersSpecCLI.js:429:3379)
[61879 ms]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[61879 ms]     at async utA (/root/.vscode-remote-containers/dist/dev-containers-cli-0.362.0/dist/spec-node/devContainersSpecCLI.js:409:3486)
[61879 ms]     at async KtA (/root/.vscode-remote-containers/dist/dev-containers-cli-0.362.0/dist/spec-node/devContainersSpecCLI.js:481:3865)
[61879 ms]     at async $C (/root/.vscode-remote-containers/dist/dev-containers-cli-0.362.0/dist/spec-node/devContainersSpecCLI.js:481:4807)
[61879 ms]     at async hrA (/root/.vscode-remote-containers/dist/dev-containers-cli-0.362.0/dist/spec-node/devContainersSpecCLI.js:661:13255)
[61879 ms]     at async lrA (/root/.vscode-remote-containers/dist/dev-containers-cli-0.362.0/dist/spec-node/devContainersSpecCLI.js:661:12996)
[61887 ms] Exit code 1
[61887 ms] Start: Run: docker rm -f d69a6c5c2d712a2005b5f5f60e5433a22bc86827fcee271d97f12c03dc7c9387
[61892 ms] Command failed: node /root/.vscode-remote-containers/dist/dev-containers-cli-0.362.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-9ea62ec8-a509-4485-a9f4-7efd0460aa9d1717443598952 --workspace-folder /workspaces/book-store --workspace-mount-consistency cached --id-label vsch.local.repository=https://github.com/cZalyun/book-store --id-label vsch.local.repository.volume=book-store-bffdfc0c4dde63e0468df7dbc314b699afa6ae90f75895e1b30cb10fec68a5e4 --id-label vsch.local.repository.folder=book-store --id-label devcontainer.config_file=/workspaces/book-store/.devcontainer/devcontainer.json --log-level debug --log-format json --config /workspaces/book-store/.devcontainer/devcontainer.json --override-config /tmp/devcontainer-b83abd70-e6e1-451a-a147-c144849f4fe2.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=book-store-bffdfc0c4dde63e0468df7dbc314b699afa6ae90f75895e1b30cb10fec68a5e4,target=/workspaces,external=true --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default off --mount-workspace-git-root --terminal-columns 163 --terminal-rows 32
[61892 ms] Exit code 1
[61945 ms] Container server terminated (code: 137, signal: null).`

**Comment by cZalyun** [comment]
also
`Error response from daemon: error while creating mount source path '/host_mnt/workspaces/book-store/README.md': mkdir /host_mnt/workspaces: read-only file system`

**Comment by 95gabor** [comment]
I think you found the solution for the fist problem: https://code.visualstudio.com/docs/devcontainers/tips-and-tricks#_enabling-file-sharing-in-docker-desktop I will add this to the readme.


> also `Error response from daemon: error while creating mount source path '/host_mnt/workspaces/book-store/README.md': mkdir /host_mnt/workspaces: read-only file system`

If you remove the volume mount in a recovery container it starts as expected. It look like something wrong with the vscode bootstrap container.

**Comment by 95gabor** [comment]
@cZalyun  I made some changes. Please check and test it.

**Comment by cZalyun** [comment]
I've tried with the latest version of vs-code and it is working as expected.
Thanks for your help!
